server:
    port: 8001


spring:
    application:
      name: cloud-payment-service
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.git.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://47.100.240.175:3306/vehicleplatform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: now
    password: Heycars@2019

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vehicle.platform.dao

